# This workflow is triggered on pull request events and runs the ChatGPT-CodeReview action. As of now it is disabled and moved out of the workflows folder.
# When we want to enable it, we can move it back to the workflows folder and rename it to cr.yml

name: Code Review
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
